name: Build Celeste Studio

on:
  workflow_call:
    inputs:
      build-cfg:
        required: true
        type: string
        default: Release
    outputs:
      windows_cache_key:
        value: ${{ jobs.cache.outputs.windows_cache_key }}
      linux_cache_key:
        value: ${{ jobs.cache.outputs.linux_cache_key }}
      macos_cache_key:
        value: ${{ jobs.cache.outputs.macos_cache_key }}
      windows_cache_hit:
        value: ${{ jobs.cache.outputs.windows_cache_hit }}
      linux_cache_hit:
        value: ${{ jobs.cache.outputs.linux_cache_hit }}
      macos_cache_hit:
        value: ${{ jobs.cache.outputs.macos_cache_hit }}

jobs:
  cache:
    name: Cache
    runs-on: ubuntu-latest

    outputs:
      windows_cache_key: ${{ steps.compute-key.outputs.windows_key }}
      linux_cache_key: ${{ steps.compute-key.outputs.linux_key }}
      macos_cache_key: ${{ steps.compute-key.outputs.macos_key }}
      windows_cache_hit: ${{ steps.check-windows.outputs.cache-hit }}
      linux_cache_hit: ${{ steps.check-linux.outputs.cache-hit }}
      macos_cache_hit: ${{ steps.check-macos.outputs.cache-hit }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compute cache keys
        id: compute-key
        run: |
          echo "windows_key=CelesteStudio-Windows-${{ inputs.build-cfg }}-$(find StudioCommunication Studio/CelesteStudio Studio/CelesteStudio.WPF -type f -exec sha256sum {} + | sort | sha256sum | awk '{print $1}')" >> $GITHUB_OUTPUT
          echo "linux_key=CelesteStudio-Linux-${{ inputs.build-cfg }}-$(find StudioCommunication Studio/CelesteStudio Studio/CelesteStudio.GTK -type f -exec sha256sum {} + | sort | sha256sum | awk '{print $1}')" >> $GITHUB_OUTPUT
          echo "macos_key=CelesteStudio-macOS-${{ inputs.build-cfg }}-$(find StudioCommunication Studio/CelesteStudio Studio/CelesteStudio.Mac -type f -exec sha256sum {} + | sort | sha256sum | awk '{print $1}')" >> $GITHUB_OUTPUT

      - name: Check Windows cache
        id: check-windows
        uses: actions/cache/restore@v4
        with:
          path: CelesteStudio-windows-x64.zip
          key: ${{ steps.compute-key.outputs.windows_key }}
      - name: Check Linux cache
        id: check-linux
        uses: actions/cache/restore@v4
        with:
          path: CelesteStudio-linux-x64.zip
          key: ${{ steps.compute-key.outputs.linux_key }}
      - name: Check macOS cache
        id: check-macos
        uses: actions/cache/restore@v4
        with:
          path: |
            CelesteStudio-macos-x64.zip
            CelesteStudio-macos-arm64.zip
          key: ${{ steps.compute-key.outputs.macos_key }}

      - name: Upload Windows x64
        uses: actions/upload-artifact@v4
        if: steps.check-windows.outputs.cache-hit == 'true'
        with:
          name: CelesteStudio-windows-x64
          path: CelesteStudio-windows-x64.zip
      - name: Upload Linux x64
        uses: actions/upload-artifact@v4
        if: steps.check-linux.outputs.cache-hit == 'true'
        with:
          name: CelesteStudio-linux-x64
          path: CelesteStudio-linux-x64.zip
      - name: Upload macOS x64
        uses: actions/upload-artifact@v4
        if: steps.check-macos.outputs.cache-hit == 'true'
        with:
          name: CelesteStudio-macos-x64
          path: CelesteStudio-macos-x64.zip
      - name: Upload macOS ARM64
        uses: actions/upload-artifact@v4
        if: steps.check-macos.outputs.cache-hit == 'true'
        with:
          name: CelesteStudio-macos-arm64
          path: CelesteStudio-macos-arm64.zip

  build-windows:
    name: Windows
    runs-on: windows-latest

    needs: cache
    if: needs.cache.outputs.windows_cache_hit != 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'

      - name: Set version suffix (release)
        run: sed -i "s/-dev//" Studio/CelesteStudio/Studio.cs
        if: ${{ inputs.build-cfg == 'Release' }}
      - name: Set version suffix (nightly)
        run: sed -i "s/-dev/-$(git rev-parse --short HEAD)/" Studio/CelesteStudio/Studio.cs
        if: ${{ inputs.build-cfg == 'Debug' }}

      - name: Download changelogs
        uses: actions/download-artifact@v4
        with:
          pattern: changelog-*
        if: ${{ inputs.build-cfg == 'Release' }}
      - name: Move changelogs into Assets
        run: |
          mv changelog-version/version_info.txt Studio/CelesteStudio/Assets/VersionInfo.txt
          mv changelog-studio/studio_changelog.md Studio/CelesteStudio/Assets/Changelog.md
        if: ${{ inputs.build-cfg == 'Release' }}

      - name: Publish x64
        run: dotnet publish Studio/CelesteStudio.WPF -c ${{ inputs.build-cfg }} -r win-x64 --output build-x64

      - name: Remove platform suffix
        run: mv build-x64/CelesteStudio.WPF.exe build-x64/CelesteStudio.exe

      - name: Generate archive
        run: |
          Push-Location build-x64
          Compress-Archive -Destination ../CelesteStudio-windows-x64.zip -Path **
          Pop-Location

      - name: Upload x64
        uses: actions/upload-artifact@v4
        with:
          name: CelesteStudio-windows-x64
          path: CelesteStudio-windows-x64.zip

  build-linux:
    name: Linux
    runs-on: ubuntu-latest

    needs: cache
    if: needs.cache.outputs.linux_cache_hit != 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'

      - name: Set version suffix (release)
        run: sed -i "s/-dev//" Studio/CelesteStudio/Studio.cs
        if: ${{ inputs.build-cfg == 'Release' }}
      - name: Set version suffix (nightly)
        run: sed -i "s/-dev/-$(git rev-parse --short HEAD)/" Studio/CelesteStudio/Studio.cs
        if: ${{ inputs.build-cfg == 'Debug' }}

      - name: Download changelogs
        uses: actions/download-artifact@v4
        with:
          pattern: changelog-*
        if: ${{ inputs.build-cfg == 'Release' }}
      - name: Move changelogs into Assets
        run: |
          mv changelog-version/version_info.txt Studio/CelesteStudio/Assets/VersionInfo.txt
          mv changelog-studio/studio_changelog.md Studio/CelesteStudio/Assets/Changelog.md
        if: ${{ inputs.build-cfg == 'Release' }}

      - name: Publish x64
        run: dotnet publish Studio/CelesteStudio.GTK -c ${{ inputs.build-cfg }} -r linux-x64 --output build-x64

      - name: Remove platform suffix
        run: mv build-x64/CelesteStudio.GTK build-x64/CelesteStudio

      - name: Generate archive
        run: |
          pushd build-x64
          zip -r ../CelesteStudio-linux-x64.zip **
          popd

      - name: Upload x64
        uses: actions/upload-artifact@v4
        with:
          name: CelesteStudio-linux-x64
          path: CelesteStudio-linux-x64.zip

  build-mac:
    name: macOS
    runs-on: macos-13

    needs: cache
    if: needs.cache.outputs.macos_cache_hit != 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'
      - name: Install macOS workflow
        run: dotnet workload install macos
      - name: Switch XCode
        run: sudo xcode-select -switch /Applications/Xcode_15.1.app/Contents/Developer

      - name: Set version suffix (release)
        run: sed -i '' -e "s/-dev//" Studio/CelesteStudio/Studio.cs
        if: ${{ inputs.build-cfg == 'Release' }}
      - name: Set version suffix (nightly)
        run: zsh -c "sed -i '' -e "s/-dev/-$(git rev-parse --short HEAD)/" Studio/CelesteStudio/Studio.cs"
        if: ${{ inputs.build-cfg == 'Debug' }}

      - name: Download changelogs
        uses: actions/download-artifact@v4
        with:
          pattern: changelog-*
        if: ${{ inputs.build-cfg == 'Release' }}
      - name: Move changelogs into Assets
        run: |
          mv changelog-version/version_info.txt Studio/CelesteStudio/Assets/VersionInfo.txt
          mv changelog-studio/studio_changelog.md Studio/CelesteStudio/Assets/Changelog.md
        if: ${{ inputs.build-cfg == 'Release' }}

      - name: Publish x64
        run: dotnet publish Studio/CelesteStudio.Mac -c ${{ inputs.build-cfg }} -r osx-x64 --output build-x64
      - name: Publish ARM64
        run: dotnet publish Studio/CelesteStudio.Mac -c ${{ inputs.build-cfg }} -r osx-arm64 --output build-arm64

      - name: Remove platform suffix
        run: |
          pushd build-x64
          mv CelesteStudio.Mac.app CelesteStudio.app
          mv CelesteStudio.app/Contents/MacOS/CelesteStudio.Mac CelesteStudio.app/Contents/MacOS/CelesteStudio
          mv CelesteStudio.app/Contents/MacOS/CelesteStudio.Mac.app CelesteStudio.app/Contents/MacOS/CelesteStudio.app
          sed -i '' -e 's/CelesteStudio.Mac/CelesteStudio/' CelesteStudio.app/Contents/Info.plist
          popd
          
          pushd build-arm64
          mv CelesteStudio.Mac.app CelesteStudio.app
          mv CelesteStudio.app/Contents/MacOS/CelesteStudio.Mac CelesteStudio.app/Contents/MacOS/CelesteStudio
          mv CelesteStudio.app/Contents/MacOS/CelesteStudio.Mac.app CelesteStudio.app/Contents/MacOS/CelesteStudio.app
          sed -i '' -e 's/CelesteStudio.Mac/CelesteStudio/' CelesteStudio.app/Contents/Info.plist
          popd

      - name: Generate archive
        run: |
          pushd build-x64
          zip -r ../CelesteStudio-macos-x64.zip CelesteStudio.app
          popd
          
          pushd build-arm64
          zip -r ../CelesteStudio-macos-arm64.zip CelesteStudio.app
          popd

      - name: Upload x64
        uses: actions/upload-artifact@v4
        with:
          name: CelesteStudio-macos-x64
          path: CelesteStudio-macos-x64.zip
      - name: Upload ARM64
        uses: actions/upload-artifact@v4
        with:
          name: CelesteStudio-macos-arm64
          path: CelesteStudio-macos-arm64.zip
